/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_api_v1_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Directions */
        get: operations["list_directions_api_v1_directions_get"];
        put?: never;
        /** Create Direction */
        post: operations["create_direction_api_v1_directions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/directions/{direction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Direction */
        patch: operations["patch_direction_api_v1_directions__direction_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Protocol */
        get: operations["export_protocol_api_v1_meetings__meeting_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/sed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push To Sed */
        post: operations["push_to_sed_api_v1_meetings__meeting_id__sed_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Meetings */
        get: operations["list_meetings_api_v1_meetings_get"];
        put?: never;
        /** Create Meeting */
        post: operations["create_meeting_api_v1_meetings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Live Meeting
         * @description Create a meeting to be fed by the browser over WS /meetings/{id}/live.
         */
        post: operations["create_live_meeting_api_v1_meetings_live_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/bot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Bot Meeting
         * @description Create a meeting and dispatch the bot to join the call.
         */
        post: operations["create_bot_meeting_api_v1_meetings_bot_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Meeting Audio
         * @description Attach a recording to an existing meeting (bot callback or manual re-upload).
         *
         *     Auth: either the bot token header or a logged-in editor.
         */
        post: operations["upload_meeting_audio_api_v1_meetings__meeting_id__audio_post"];
        /** Delete Audio */
        delete: operations["delete_audio_api_v1_meetings__meeting_id__audio_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meeting */
        get: operations["get_meeting_api_v1_meetings__meeting_id__get"];
        put?: never;
        post?: never;
        /** Delete Meeting */
        delete: operations["delete_meeting_api_v1_meetings__meeting_id__delete"];
        options?: never;
        head?: never;
        /** Patch Meeting */
        patch: operations["patch_meeting_api_v1_meetings__meeting_id__patch"];
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/speakers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Speakers */
        put: operations["set_speakers_api_v1_meetings__meeting_id__speakers_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Meeting */
        post: operations["confirm_meeting_api_v1_meetings__meeting_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meetings/{meeting_id}/reprocess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reprocess Meeting */
        post: operations["reprocess_meeting_api_v1_meetings__meeting_id__reprocess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Notifications */
        get: operations["list_notifications_api_v1_notifications_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unread Count */
        get: operations["unread_count_api_v1_notifications_unread_count_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notification_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Read */
        post: operations["mark_read_api_v1_notifications__notification_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark All Read */
        post: operations["mark_all_read_api_v1_notifications_read_all_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Participants */
        get: operations["list_participants_api_v1_participants_get"];
        put?: never;
        /** Create Participant */
        post: operations["create_participant_api_v1_participants_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/participants/{participant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Participant */
        delete: operations["delete_participant_api_v1_participants__participant_id__delete"];
        options?: never;
        head?: never;
        /** Patch Participant */
        patch: operations["patch_participant_api_v1_participants__participant_id__patch"];
        trace?: never;
    };
    "/api/v1/participants/{participant_id}/voiceprint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Voiceprint */
        post: operations["enroll_voiceprint_api_v1_participants__participant_id__voiceprint_post"];
        /** Delete Voiceprint */
        delete: operations["delete_voiceprint_api_v1_participants__participant_id__voiceprint_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tasks */
        get: operations["list_tasks_api_v1_tasks_get"];
        put?: never;
        /** Create Task */
        post: operations["create_task_api_v1_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Task Stats */
        get: operations["task_stats_api_v1_tasks_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Task */
        delete: operations["delete_task_api_v1_tasks__task_id__delete"];
        options?: never;
        head?: never;
        /** Patch Task */
        patch: operations["patch_task_api_v1_tasks__task_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_meeting_api_v1_meetings_post */
        Body_create_meeting_api_v1_meetings_post: {
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /** File */
            file: string;
            /** @default ru */
            output_language: components["schemas"]["Locale"];
            /** Participant Ids */
            participant_ids?: number[] | null;
        };
        /** Body_enroll_voiceprint_api_v1_participants__participant_id__voiceprint_post */
        Body_enroll_voiceprint_api_v1_participants__participant_id__voiceprint_post: {
            /** File */
            file: string;
        };
        /** Body_upload_meeting_audio_api_v1_meetings__meeting_id__audio_post */
        Body_upload_meeting_audio_api_v1_meetings__meeting_id__audio_post: {
            /** File */
            file: string;
        };
        /** BotMeetingIn */
        BotMeetingIn: {
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /** @default ru */
            output_language: components["schemas"]["Locale"];
            /** Participant Ids */
            participant_ids?: number[];
            /** Platform */
            platform: string;
            /** Url */
            url: string;
        };
        /** DirectionIn */
        DirectionIn: {
            /** Name */
            name: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** DirectionOut */
        DirectionOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Is Active */
            is_active: boolean;
        };
        /** DirectionPatch */
        DirectionPatch: {
            /** Name */
            name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LiveMeetingIn */
        LiveMeetingIn: {
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            /** @default ru */
            output_language: components["schemas"]["Locale"];
            /** Participant Ids */
            participant_ids?: number[];
        };
        /**
         * Locale
         * @enum {string}
         */
        Locale: "ru" | "kk";
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** MeetingDetail */
        MeetingDetail: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            source: components["schemas"]["MeetingSource"];
            /** Platform */
            platform: string | null;
            /** Audio Path */
            audio_path: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            output_language: components["schemas"]["Locale"];
            status: components["schemas"]["MeetingStatus"];
            /** Progress Stage */
            progress_stage: string | null;
            /** Progress Pct */
            progress_pct: number;
            /** Error */
            error: string | null;
            /** Sed Ref */
            sed_ref: string | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Tasks Count
             * @default 0
             */
            tasks_count: number;
            /**
             * Participants Count
             * @default 0
             */
            participants_count: number;
            /** Summary */
            summary: string | null;
            /** Language Stats */
            language_stats: {
                [key: string]: unknown;
            } | null;
            /** Model Info */
            model_info: {
                [key: string]: unknown;
            } | null;
            /** Participants */
            participants: components["schemas"]["ParticipantOut"][];
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Speaker Map */
            speaker_map: components["schemas"]["SpeakerMapOut"][];
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
        };
        /** MeetingOut */
        MeetingOut: {
            /** Id */
            id: number;
            /** Title */
            title: string;
            /**
             * Meeting Date
             * Format: date
             */
            meeting_date: string;
            source: components["schemas"]["MeetingSource"];
            /** Platform */
            platform: string | null;
            /** Audio Path */
            audio_path: string | null;
            /** Duration Sec */
            duration_sec: number | null;
            output_language: components["schemas"]["Locale"];
            status: components["schemas"]["MeetingStatus"];
            /** Progress Stage */
            progress_stage: string | null;
            /** Progress Pct */
            progress_pct: number;
            /** Error */
            error: string | null;
            /** Sed Ref */
            sed_ref: string | null;
            /** Created By */
            created_by: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Confirmed At */
            confirmed_at: string | null;
            /**
             * Tasks Count
             * @default 0
             */
            tasks_count: number;
            /**
             * Participants Count
             * @default 0
             */
            participants_count: number;
        };
        /** MeetingPatch */
        MeetingPatch: {
            /** Title */
            title?: string | null;
            /** Meeting Date */
            meeting_date?: string | null;
            /** Summary */
            summary?: string | null;
            output_language?: components["schemas"]["Locale"] | null;
            /** Participant Ids */
            participant_ids?: number[] | null;
        };
        /**
         * MeetingSource
         * @enum {string}
         */
        MeetingSource: "upload" | "live" | "bot";
        /**
         * MeetingStatus
         * @enum {string}
         */
        MeetingStatus: "uploaded" | "processing" | "draft" | "confirmed" | "failed";
        /**
         * NotificationKind
         * @enum {string}
         */
        NotificationKind: "assigned" | "due_soon" | "overdue" | "protocol_ready";
        /** NotificationOut */
        NotificationOut: {
            /** Id */
            id: number;
            kind: components["schemas"]["NotificationKind"];
            /** Title */
            title: string;
            /** Body */
            body: string;
            /** Task Id */
            task_id: number | null;
            /** Meeting Id */
            meeting_id: number | null;
            /** Read At */
            read_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ParticipantIn */
        ParticipantIn: {
            /** Name */
            name: string;
            /** Email */
            email?: string | null;
            /** Position */
            position?: string | null;
        };
        /** ParticipantOut */
        ParticipantOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Email */
            email: string | null;
            /** Position */
            position: string | null;
            /** User Id */
            user_id: number | null;
            /**
             * Has Voiceprint
             * @default false
             */
            has_voiceprint: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ParticipantPatch */
        ParticipantPatch: {
            /** Name */
            name?: string | null;
            /** Email */
            email?: string | null;
            /** Position */
            position?: string | null;
        };
        /** RegisterIn */
        RegisterIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /** @default ru */
            locale: components["schemas"]["Locale"];
        };
        /** SegmentOut */
        SegmentOut: {
            /** Idx */
            idx: number;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Speaker */
            speaker: string;
            /** Text */
            text: string;
            /** Lang */
            lang: string;
        };
        /** SpeakerMapIn */
        SpeakerMapIn: {
            /** Speaker */
            speaker: string;
            /** Participant Id */
            participant_id: number | null;
        };
        /** SpeakerMapOut */
        SpeakerMapOut: {
            /** Speaker */
            speaker: string;
            /** Participant Id */
            participant_id: number | null;
            source: components["schemas"]["SpeakerSource"];
            /** Confidence */
            confidence: number;
        };
        /**
         * SpeakerSource
         * @enum {string}
         */
        SpeakerSource: "voiceprint" | "llm" | "manual" | "none";
        /** TaskCreate */
        TaskCreate: {
            /** Meeting Id */
            meeting_id: number;
            /** Text */
            text: string;
            /** Assignee Participant Id */
            assignee_participant_id?: number | null;
            /**
             * Assignee Name
             * @default
             */
            assignee_name: string;
            /** Deadline */
            deadline?: string | null;
            /** Deadline Raw */
            deadline_raw?: string | null;
            /** @default normal */
            urgency: components["schemas"]["Urgency"];
            /** Direction Id */
            direction_id?: number | null;
            /** Quote */
            quote?: string | null;
            /** Segment Idx */
            segment_idx?: number | null;
        };
        /** TaskOut */
        TaskOut: {
            /** Id */
            id: number;
            /** Meeting Id */
            meeting_id: number;
            /** Assignee Participant Id */
            assignee_participant_id: number | null;
            /** Assignee Name */
            assignee_name: string;
            /** Text */
            text: string;
            /** Deadline */
            deadline: string | null;
            /** Deadline Raw */
            deadline_raw: string | null;
            urgency: components["schemas"]["Urgency"];
            /** Direction Id */
            direction_id: number | null;
            /** Direction Name */
            direction_name?: string | null;
            /** Quote */
            quote: string | null;
            /** Segment Idx */
            segment_idx: number | null;
            /** Confidence */
            confidence: number;
            status: components["schemas"]["TaskStatus"];
            /** Sed Ref */
            sed_ref: string | null;
            /** Meeting Title */
            meeting_title?: string | null;
            /** Meeting Date */
            meeting_date?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Done At */
            done_at: string | null;
        };
        /** TaskPatch */
        TaskPatch: {
            /** Text */
            text?: string | null;
            /** Assignee Participant Id */
            assignee_participant_id?: number | null;
            /** Assignee Name */
            assignee_name?: string | null;
            /** Deadline */
            deadline?: string | null;
            /** Deadline Raw */
            deadline_raw?: string | null;
            urgency?: components["schemas"]["Urgency"] | null;
            /** Direction Id */
            direction_id?: number | null;
            status?: components["schemas"]["TaskStatus"] | null;
        };
        /** TaskStats */
        TaskStats: {
            /**
             * Draft
             * @default 0
             */
            draft: number;
            /**
             * Confirmed
             * @default 0
             */
            confirmed: number;
            /**
             * In Progress
             * @default 0
             */
            in_progress: number;
            /**
             * Done
             * @default 0
             */
            done: number;
            /**
             * Overdue
             * @default 0
             */
            overdue: number;
            /**
             * Due Soon
             * @default 0
             */
            due_soon: number;
            /**
             * Total
             * @default 0
             */
            total: number;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "draft" | "confirmed" | "in_progress" | "done" | "overdue";
        /** UnreadCount */
        UnreadCount: {
            /** Unread */
            unread: number;
        };
        /**
         * Urgency
         * @enum {string}
         */
        Urgency: "low" | "normal" | "high" | "critical";
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Name */
            name: string;
            role: components["schemas"]["UserRole"];
            locale: components["schemas"]["Locale"];
            /** Participant Id */
            participant_id?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "user" | "admin";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VoiceprintOut */
        VoiceprintOut: {
            /** Ok */
            ok: boolean;
            /** Embedding Dim */
            embedding_dim: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string | boolean;
                    };
                };
            };
        };
    };
    register_api_v1_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_directions_api_v1_directions_get: {
        parameters: {
            query?: {
                include_inactive?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_direction_api_v1_directions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_direction_api_v1_directions__direction_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                direction_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DirectionPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DirectionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_protocol_api_v1_meetings__meeting_id__export_get: {
        parameters: {
            query?: {
                format?: "docx" | "pdf";
                lang?: ("ru" | "kk") | null;
            };
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_to_sed_api_v1_meetings__meeting_id__sed_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_meetings_api_v1_meetings_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["MeetingStatus"] | null;
                date_from?: string | null;
                date_to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_meeting_api_v1_meetings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_meeting_api_v1_meetings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_live_meeting_api_v1_meetings_live_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LiveMeetingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_bot_meeting_api_v1_meetings_bot_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BotMeetingIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_meeting_audio_api_v1_meetings__meeting_id__audio_post: {
        parameters: {
            query?: never;
            header?: {
                "x-bot-token"?: string | null;
            };
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_meeting_audio_api_v1_meetings__meeting_id__audio_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_audio_api_v1_meetings__meeting_id__audio_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_meeting_api_v1_meetings__meeting_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_meeting_api_v1_meetings__meeting_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_meeting_api_v1_meetings__meeting_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeetingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_speakers_api_v1_meetings__meeting_id__speakers_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerMapIn"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_meeting_api_v1_meetings__meeting_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reprocess_meeting_api_v1_meetings__meeting_id__reprocess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                meeting_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeetingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_notifications_api_v1_notifications_get: {
        parameters: {
            query?: {
                unread?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unread_count_api_v1_notifications_unread_count_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_read_api_v1_notifications__notification_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_all_read_api_v1_notifications_read_all_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnreadCount"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_participants_api_v1_participants_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_participant_api_v1_participants_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_participant_api_v1_participants__participant_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_participant_api_v1_participants__participant_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParticipantPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParticipantOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_voiceprint_api_v1_participants__participant_id__voiceprint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_enroll_voiceprint_api_v1_participants__participant_id__voiceprint_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceprintOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_voiceprint_api_v1_participants__participant_id__voiceprint_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                participant_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tasks_api_v1_tasks_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TaskStatus"] | null;
                assignee_id?: number | null;
                direction_id?: number | null;
                urgency?: components["schemas"]["Urgency"] | null;
                meeting_id?: number | null;
                mine?: boolean;
                include_draft?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_api_v1_tasks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    task_stats_api_v1_tasks_stats_get: {
        parameters: {
            query?: {
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskStats"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_api_v1_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_task_api_v1_tasks__task_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: number;
            };
            cookie?: {
                access_token?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
