/**
 * Typed fetch wrapper for the backend REST API.
 * Types come from `src/lib/api-types.ts` (generated by `pnpm gen:api` from backend openapi.json).
 * Cookies (JWT) are sent automatically with `credentials: "include"`.
 */
import type { components } from "./api-types";

export const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000/api/v1";
export const WS_URL = API_URL.replace(/^http/, "ws");

export class ApiError extends Error {
  constructor(
    public status: number,
    public detail: unknown,
  ) {
    super(typeof detail === "string" ? detail : `API error ${status}`);
  }
}

type Method = "GET" | "POST" | "PUT" | "PATCH" | "DELETE";

export async function api<T = unknown>(
  path: string,
  init: { method?: Method; json?: unknown; form?: FormData; query?: Record<string, unknown> } = {},
): Promise<T> {
  const url = new URL(API_URL + path);
  for (const [k, v] of Object.entries(init.query ?? {})) {
    if (v === undefined || v === null || v === "") continue;
    if (Array.isArray(v)) v.forEach((x) => url.searchParams.append(k, String(x)));
    else url.searchParams.set(k, String(v));
  }
  const res = await fetch(url, {
    method: init.method ?? "GET",
    credentials: "include",
    headers: init.json ? { "Content-Type": "application/json" } : undefined,
    body: init.json ? JSON.stringify(init.json) : init.form,
    cache: "no-store",
  });
  if (res.status === 204) return undefined as T;
  const body = res.headers.get("content-type")?.includes("json") ? await res.json() : await res.blob();
  if (!res.ok) throw new ApiError(res.status, (body as { detail?: unknown })?.detail ?? body);
  return body as T;
}

export type Schemas = components["schemas"];
export type User = Schemas["UserOut"];
export type Participant = Schemas["ParticipantOut"];
export type Direction = Schemas["DirectionOut"];
export type Meeting = Schemas["MeetingOut"];
export type MeetingDetail = Schemas["MeetingDetail"];
export type Task = Schemas["TaskOut"];
export type TaskStats = Schemas["TaskStats"];
export type Notification = Schemas["NotificationOut"];
export type Segment = Schemas["SegmentOut"];
export type SpeakerMap = Schemas["SpeakerMapOut"];

export const auth = {
  me: () => api<User>("/auth/me"),
  login: (email: string, password: string) => api<User>("/auth/login", { method: "POST", json: { email, password } }),
  register: (body: { email: string; password: string; name: string; locale: "ru" | "kk" }) =>
    api<User>("/auth/register", { method: "POST", json: body }),
  logout: () => api<void>("/auth/logout", { method: "POST" }),
};

export const meetings = {
  list: (query?: { status?: string; date_from?: string; date_to?: string }) => api<Meeting[]>("/meetings", { query }),
  get: (id: number) => api<MeetingDetail>(`/meetings/${id}`),
  upload: (form: FormData) => api<Meeting>("/meetings", { method: "POST", form }),
  createLive: (body: { title: string; meeting_date: string; output_language?: "ru" | "kk"; participant_ids?: number[] }) =>
    api<Meeting>("/meetings/live", { method: "POST", json: body }),
  createBot: (body: { title: string; meeting_date: string; platform: "meet" | "zoom" | "teams"; url: string; participant_ids?: number[] }) =>
    api<Meeting>("/meetings/bot", { method: "POST", json: body }),
  liveSocket: (id: number) => new WebSocket(`${WS_URL}/meetings/${id}/live`),
  patch: (id: number, body: Partial<{ title: string; meeting_date: string; summary: string; participant_ids: number[] }>) =>
    api<MeetingDetail>(`/meetings/${id}`, { method: "PATCH", json: body }),
  setSpeakers: (id: number, map: { speaker: string; participant_id: number | null }[]) =>
    api<MeetingDetail>(`/meetings/${id}/speakers`, { method: "PUT", json: map }),
  confirm: (id: number) => api<MeetingDetail>(`/meetings/${id}/confirm`, { method: "POST" }),
  reprocess: (id: number) => api<Meeting>(`/meetings/${id}/reprocess`, { method: "POST" }),
  exportUrl: (id: number, format: "docx" | "pdf", lang: "ru" | "kk") => `${API_URL}/meetings/${id}/export?format=${format}&lang=${lang}`,
  sendToSed: (id: number) => api<{ sed_ref: string; outbox_path: string }>(`/meetings/${id}/sed`, { method: "POST" }),
  deleteAudio: (id: number) => api<void>(`/meetings/${id}/audio`, { method: "DELETE" }),
  remove: (id: number) => api<void>(`/meetings/${id}`, { method: "DELETE" }),
};

export const tasks = {
  list: (query?: { status?: string; assignee_id?: number; direction_id?: number; urgency?: string; meeting_id?: number; mine?: boolean; include_draft?: boolean }) =>
    api<Task[]>("/tasks", { query }),
  stats: (mine = false) => api<TaskStats>("/tasks/stats", { query: { mine } }),
  create: (body: { meeting_id: number; text: string; assignee_participant_id?: number | null; deadline?: string | null; urgency?: string; direction_id?: number | null }) =>
    api<Task>("/tasks", { method: "POST", json: body }),
  patch: (id: number, body: Partial<{ text: string; assignee_participant_id: number | null; deadline: string | null; urgency: string; direction_id: number | null; status: string }>) =>
    api<Task>(`/tasks/${id}`, { method: "PATCH", json: body }),
  remove: (id: number) => api<void>(`/tasks/${id}`, { method: "DELETE" }),
};

export const participants = {
  list: () => api<Participant[]>("/participants"),
  create: (body: { name: string; email?: string; position?: string }) => api<Participant>("/participants", { method: "POST", json: body }),
  patch: (id: number, body: Partial<{ name: string; email: string; position: string }>) => api<Participant>(`/participants/${id}`, { method: "PATCH", json: body }),
  enrollVoice: (id: number, blob: Blob) => {
    const form = new FormData();
    form.append("file", blob, "sample.webm");
    return api<{ ok: boolean; embedding_dim: number }>(`/participants/${id}/voiceprint`, { method: "POST", form });
  },
  deleteVoice: (id: number) => api<void>(`/participants/${id}/voiceprint`, { method: "DELETE" }),
};

export const directions = {
  list: (includeInactive = false) => api<Direction[]>("/directions", { query: { include_inactive: includeInactive } }),
  create: (body: { name: string; is_active?: boolean }) => api<Direction>("/directions", { method: "POST", json: body }),
  patch: (id: number, body: Partial<{ name: string; is_active: boolean }>) => api<Direction>(`/directions/${id}`, { method: "PATCH", json: body }),
};

export const notifications = {
  list: (unread = false) => api<Notification[]>("/notifications", { query: { unread } }),
  unreadCount: () => api<{ unread: number }>("/notifications/unread-count"),
  read: (id: number) => api<Notification>(`/notifications/${id}/read`, { method: "POST" }),
  readAll: () => api<{ unread: number }>("/notifications/read-all", { method: "POST" }),
};
